#List of all modules and the corresponding jsp's
#-----------------------------------------------
moduleName: Picture
moduleIcon: IMAGES/CuppaWEB/camera.png
moduleDescription: Use this element to add a picture to your page.
moduleDefaultXML: <picture><id></id><descriptive_name></descriptive_name><picture_path><![CDATA[/system/CuppaWEB.png]]></picture_path><position><![CDATA[left]]></position><picturetitle></picturetitle><alt_attribute></alt_attribute><border><![CDATA[0]]></border><popup_picture></popup_picture><popup_alt_attribute></popup_alt_attribute><popup_title></popup_title><visible><![CDATA[true]]></visible><picture_link_target><![CDATA[_self]]></picture_link_target><picture_link></picture_link><padding_bottom></padding_bottom><padding_top></padding_top><padding_right></padding_right><padding_left></padding_left></picture>


fop: com.cuppait.cuppaweb.outputrenderers.xml_pdffop.Picture
pdf: com.cuppait.cuppaweb.outputrenderers.xml_pdf.Picture
link: /global/modules/picture.jsp
eml: /global/modules/picture.jsp
type: simple


xmlSessionId_0: picture-data
xmlParentNode_0: picture/
xmlDataToLoad_0: position/picture_path/picturetitle/alt_attribute/border/padding_left/padding_right/padding_top/padding_bottom/
xmlDataMultiple_0: false

xmlSessionId_1: popup-data
xmlParentNode_1: picture/
xmlDataToLoad_1: popup_picture/popup_alt_attribute/popup_title
xmlDataMultiple_1: false
