#CuppaWEB Mime Types
#Tue Jul 28 08:43:12 WST 2009
snd: audio/basic
mid: audio/midi
php: application/x-httpd-php
tar: application/x-tar
wz: application/x-Wingz
eps: application/postscript
qt: video/quicktime
ico: image/x-icon
rtf: text/rtf
tsv: text/tab-separated-values
movie: video/x-sgi-movie
png: image/png
sgm: text/sgml
xls: application/excel
ram: audio/x-pn-realaudio
mpga: audio/mpeg
ppsx: application/powerpoint
cpp: text/plain
wk: application/x-123
mp3: audio/mpeg
mp2: video/mpeg
smi: application/smil
rmm: audio/x-pn-realaudio
dvi: application/x-dvi
pgp: application/pgp
rgb: image/x-rgb
gif: image/gif
pgn: application/x-chess-pgn
wrl: x-world/x-vrml
dcr: application/x-director
js: text/javascript
jnlp: application/x-java-jnlp-file
dl: video/dl
chrt: application/x-kchart
dir: application/x-director
lha: application/octet-stream
ps: application/postscript
dot: application/msword
wrd: application/msword
avi: video/x-msvideo
vrml: x-world/x-vrml
pm: application/x-perl
pl: application/x-perl
lzh: application/octet-stream
txt: text/plain
kar: audio/midi
bin: application/octet-stream
com: application/x-msdos-program
jpeg: image/jpeg
doc: application/msword
jar: application/x-jar
htm: text/html
tex: application/x-tex
z: application/x-compress
ksp: application/x-kspread
xwd: image/x-xwindowdump
mpeg: video/mpeg
cc: text/plain
docx: application/msword
cpio: application/x-cpio
swf2: application/x-shockwave-flash
h: text/plain
c: text/plain
xpm: image/x-xpixmap
dtd: text/xml
sgml: text/sgml
latex: application/x-latex
swf: application/futurespash
zip: application/zip
dms: application/octet-stream
json: application/json
bat: application/x-msdos-program
hh: text/plain
vcs: text/x-vCalendar
css: text/css
au: audio/basic
gz: application/x-gunzip
flv: video/flash
tiff: image/tiff
csh: application/x-csh
vcf: text/x-vCard
ppt: application/powerpoint
vcd: application/x-cdlink
pps: application/powerpoint
ai: application/postscript
gtar: application/x-gtar
phtml: application/x-httpd-php
gl: video/gl
kwt: application/x-kword
pdf: application/pdf
tcl: application/x-tcl
xbm: image/x-xbitmap
asc: text/plain
ief: image/ief
midi: audio/midi
tif: image/tiff
dxr: application/x-director
kwd: application/x-kword
wp5: application/wordperfect5.1
html: text/html
exe: application/x-msdos-program
kpt: application/x-kpresenter
class: application/octet-stream
mpg: video/mpeg
bz2: application/x-bzip2
kpr: application/x-kpresenter
mpe: video/mpeg
rv: video/vnd.rn-realvideo
rt: text/vnd.rn-realtext
wav: audio/x-wav
mov: video/quicktime
wmv: video/x-ms-wmv
jpg: image/jpeg
deb: application/x-debian-package
pptx: application/powerpoint
rf: image/vnd.rn-realflash
rtx: text/richtext
jpe: image/jpeg
hpp: text/plain
hdf: application/x-hdf
xml: text/html
admin: text/html
smil: application/smil
bcpio: application/x-bcpio
ra: audio/vnd.rn-realaudio
pht: application/x-httpd-php
tgz: application/x-gtar
