#List of all modules and the corresponding jsp's
#-----------------------------------------------
moduleName: Text
moduleDescription: A simple text element, you can set properties like colour/size/font/bold/italic and underlined.
moduleIcon: IMAGES/CuppaWEB/txt.png
###################################################################
###moduleDefaultXML is the default xml descriptor for this module
###################################################################
moduleDefaultXML: <text><id></id><descriptive_name></descriptive_name><bold><![CDATA[false]]></bold><italic><![CDATA[false]]></italic><underlined><![CDATA[false]]></underlined><textcolor></textcolor><textsize><![CDATA[default]]></textsize><textalignment><![CDATA[default]]></textalignment><printtext><![CDATA[New Text Module]]></printtext><visible><![CDATA[true]]></visible></text>
type: simple

xmlSessionId_0: all-data
xmlParentNode_0: text/
xmlDataToLoad_0: bold/italic/underlined/textcolor/textsize/textalignment/printtext/
xmlDataMultiple_0: false
