#List of all modules and the corresponding jsp's
#-----------------------------------------------
moduleName: Unordered List
moduleIcon: IMAGES/CuppaWEB/view_choose.png
moduleClass: de.codefactor.web.admin.module.modules.CuppaWEBPageEditorModules.UnorderedList

moduleHelpPage: http://www.cuppait.com/CuppaAdmin_Help/ModuleUnorderedList/ModuleUnorderedList.html

pdf: com.cuppait.cuppaweb.outputrenderers.xml_pdf.UnorderedList

link: /global/modules/unorderedlist.jsp
eml: /global/modules/unorderedlist.jsp
xhtml: /xhtmlstrict/modules/unorderedlist.jsp
type: simple


xmlSessionId_0: all-data
xmlParentNode_0: unorderedlist/
xmlParentNodeMultiple_0: list_element/
xmlDataToLoad_0: list_element/
xmlDataMultiple_0: true

xmlSessionId_1: position
xmlParentNode_1: unorderedlist/
xmlDataToLoad_1: position/
xmlDataMultiple_1: false
