#List of all modules and the corresponding jsp's
#-----------------------------------------------
moduleName: News Reel
moduleDescription: A news component, links directly to a news reel.
moduleIcon: IMAGES/CuppaWEB/txt.png
###################################################################
###moduleDefaultXML is the default xml descriptor for this module
###################################################################
moduleDefaultXML: <news><id></id><descriptive_name><![CDATA[News]]></descriptive_name><path><![CDATA[/system/tmpnews.news]]></path><syndicate_feed>true</syndicate_feed><visible><![CDATA[true]]></visible></news>


link: /global/modules/news.jsp
eml: /global/modules/news.jsp
type: simple

xmlSessionId_0: news-data
xmlParentNode_0: news/
xmlDataToLoad_0: path/syndicate_feed/
xmlDataMultiple_0: false
