#List of all modules and the corresponding jsp's
#-----------------------------------------------
moduleName: CuppaBOOK
moduleIcon: IMAGES/CuppaWEB/kpersonalizer.png
moduleDescription: Use this element to import a CuppaBOOK into this page.
moduleDefaultXML: <cuppabook><id></id><descriptive_name></descriptive_name><bookpath><![CDATA[/system/DefaultBook.book]]></bookpath><visible><![CDATA[true]]></visible></cuppabook>

#pdf: com.cuppait.cuppaweb.outputrenderers.xml_pdf.ContentBlock
link: /global/modules/CuppaBOOK.jsp
eml: /global/modules/CuppaBOOK.jsp
type: full

xmlSessionId_0: all-data
xmlParentNode_0: cuppabook/
xmlDataToLoad_0: id/bookpath
xmlDataMultiple_0: false
