#List of all modules and the corresponding jsp's
#-----------------------------------------------
moduleName: CuppaFORM
moduleIcon: IMAGES/CuppaWEB/kudesigner.png
moduleDescription: Use this element to add a picture to your page.
moduleDefaultXML: <cuppa_form><id></id><descriptive_name></descriptive_name><path><![CDATA[/system/test.form]]></path><params></params><visible><![CDATA[true]]></visible></cuppa_form>


link: /global/modules/CuppaForm.jsp
eml: /global/modules/CuppaForm.jsp
type: full


xmlSessionId_0: all-data
xmlParentNode_0: cuppa_form/
xmlDataToLoad_0: path/
xmlDataMultiple_0: false


xmlSessionId_1: params
xmlParentNode_1: cuppa_form/
xmlParentNodeMultiple_1: param/
xmlDataToLoad_1: param
xmlDataMultiple_1: true
