#List of all modules and the corresponding jsp's
#-----------------------------------------------
moduleName: CuppaFORM
moduleIcon: IMAGES/CuppaWEB/kudesigner.png
moduleClass: de.codefactor.web.admin.module.modules.CuppaWEBPageEditorModules.CuppaFORMS.CuppaFORM


link: /global/modules/CuppaForm_1.jsp
eml: /global/modules/CuppaForm_1.jsp
type: full


xmlSessionId_0: all-data
xmlParentNode_0: cuppa_form_1/
xmlDataToLoad_0: path/
xmlDataMultiple_0: false


xmlSessionId_1: params
xmlParentNode_1: cuppa_form_1/
xmlParentNodeMultiple_1: param/
xmlDataToLoad_1: param
xmlDataMultiple_1: true
