#Email Contact Form Descriptor file
#-----------------------------------------------
moduleName: Email Contact Form
moduleIcon: IMAGES/CuppaWEB/xfmail.png
moduleClass: de.codefactor.web.admin.module.modules.CuppaWEBPageEditorModules.EmailContact
moduleHelpPage: http://www.cuppait.com/CuppaAdmin_Help/ModuleEmailContactForm/ModuleEmailContactForm.html

link: /global/modules/emailContact.jsp
eml: /global/modules/emailContact.jsp
type: half

xmlSessionId_0: email-contact-data
xmlParentNode_0: email_contact/
xmlDataToLoad_0: destination/mail_server/subject
xmlDataMultiple_0: false
